name: Auto Update Date

on:
  schedule:
    - cron: '0 4 * * *'  # 每天UTC时间00:00运行（北京时间08:00）
  workflow_dispatch:     # 允许手动触发

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Update Date in clash.yaml
      run: |
        python update_date.py
        cat clash.yaml  # 可选：查看修改后的文件内容

    - name: Commit Changes
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'actions@github.com'
        git add clash.yaml
        git commit -m "自动更新日期: $(date +'%Y/%m/%d')"
        git push
